### ISSUE TITLE
style transfer

### ISSUE THREAD

**Issue by stone100010** [woctezuma/stylegan2-projecting-images#6]
When I was training the '. NPY' file, '-- num steps' I used 50000 steps and' -- no tiled '. The training picture was close to the original picture. I started to carry out style transfer, The result is not good. I think it may be that the '-- num steps' in the training'. NPY 'file is not enough. Now I am continuing training with the goal of 300000' - num steps'. Once again, I would like to express my most sincere thanks!
![2020-09-24 18-15-44](https://user-images.githubusercontent.com/48286567/94134088-248c2280-fe94-11ea-88f9-a423c1c612da.png)

**Comment by woctezuma** [comment]
There is a trade-off between image quality and semantic quality, and a large number of steps improve image fidelity at the cost of semantic fidelity. I think `--num_steps` is too large (like 1 order of magnitude too large), especially with `--no_tiled` set to True. You should check [this discussion](https://github.com/rolux/stylegan2encoder/issues/2).

For questions related to StyleGAN2, I would suggest to check the popular repositories:
-   https://github.com/rolux/stylegan2encoder/issues
-   https://github.com/Puzer/stylegan-encoder/issues
-   https://github.com/pbaylies/stylegan-encoder/issues
Because in my repository with a few stars, barely nobody will check the question.
