### ISSUE TITLE
Use(load) the npy of the first picture to continue training the npy of the second picture

### ISSUE THREAD

**Issue by stone100010** [woctezuma/stylegan2-projecting-images#7]
Hello, I am trying to learn the face information of each frame in a video. For example, I have got the first frame of image through num steps 5000 times. How to use this.Npy to continue training the second frame picture? I look forward to your reply, thank you!

**Comment by woctezuma** [comment]
It is an interesting idea. I have not done it, but I think you would only have to edit:

https://github.com/NVlabs/stylegan2/blob/dae148b9bb6346b00c10f0cfc9e011b3ef0c1986/projector.py#L160-L162

```python
def start(self, target_images):
    [...]

    # Prepare target images.
    self._info('Preparing target images...')
    [...]

    # Initialize optimization state.
    self._info('Initializing optimization state...')
    tflib.set_vars({
                    self._target_images_var: target_images, 
                    self._dlatents_var: np.tile(self._dlatent_avg, [self._minibatch_size, 1, 1])
                    })
    [...]
```

so that the optimization starts from an array `w` fed as input by the user instead of always the same `w_avg`:

```python
np.tile(self._dlatent_avg, [self._minibatch_size, 1, 1])
```

It is a bit similar to the idea of improving the initialization here: https://github.com/rolux/stylegan2encoder/issues/2
