### ISSUE TITLE
Expression transfer -- angle_horizontal

### ISSUE THREAD

**Issue by stone100010** [woctezuma/stylegan2-projecting-images#8]
I tested Expression transfer, but the effect is average. You mentioned "https://github.com/a312863063/seeprettyface-face_editor". I looked at the code, which contains png and. txt files randomly generated through the trained model, and then the properties can be modified, and the performance effect is still very good. If I take a selfie with one of my photos, how to deal with the property modification? Looking forward to your answer, thank you!

**Comment by woctezuma** [comment]
As I can see in the repository which you linked to, one gets results like these:

![external repository](https://raw.githubusercontent.com/a312863063/seeprettyface-face_editor/master/examples/angle_horizontal.jpg)

In my case, it is true that the change is less important.
It seems that I had the most important changes with tiled projection `W(1,*)` (compared to no-tiled `W(18,*)`) with results such as:

![man](https://raw.githubusercontent.com/wiki/woctezuma/stylegan2-projecting-images/applications/expression/tiled/expression_42_angle_horizontal.jpg)

![woman](https://raw.githubusercontent.com/wiki/woctezuma/stylegan2-projecting-images/applications/expression/tiled/expression_07_angle_horizontal.jpg)

I have not investigated the issue more than that. I cannot really help here.
Maybe there is more information in one of the _Issues_  of the repositories there:
-   https://github.com/a312863063/generators-with-stylegan2/issues?q=is%3Aissue
-   https://github.com/a312863063/seeprettyface-face_editor/issues?q=is%3Aissue

> If I take a selfie with one of my photos, how to deal with the property modification?

You would have to encode or project the image so that you have the latent code.
Then you could modify the latent code with the property.

See:
-   https://github.com/tg-bomze/StyleGAN2-Face-Modificator
-   https://colab.research.google.com/github/tg-bomze/StyleGAN2-Face-Modificator/blob/master/Face_Modificator_with_StyleGAN2_(Eng).ipynb
